name: wilt
version: 5.0.0
description: A browser/server based CouchDB client library supporting attachments and change notification.
homepage: https://github.com/shamblett/wilt

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  crypto: "^3.0.0"
  http: "^0.13.0"
  json_object_lite: "^3.0.0"


